[package]
name = "kalman_filter"
version = "0.1.0"
edition = "2024"

[lib]

[[example]]
name = "identify_system_variances"
path = "utilities/identify_system_variance.rs"

[dependencies]
nalgebra = "0.34.0"

[dev-dependencies]
csv = "1.3.1"
serde = "1.0.228"
